version: "3"  

tasks:
  gen-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    desc: "Generate code from proto files"  
    cmds:
      - protoc -I proto proto/{{.TEXT}}/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative